spring:
  application:
    name: pdf-converter
  datasource:
    url: jdbc:postgresql://dpg-cjd2d8c5kgrc739qo200-a.oregon-postgres.render.com:5432/namaidb
    username: namaidb_user
    password: IUDMeEstcmqmii6KY5nWCI76bUy8NaFK
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: dev
  thymeleaf:
    prefix: file:src/main/resources/templates/
    suffix: .html
    mode: HTML
    cache: false
  resources:
    static-locations: file:src/main/resources/static/
    cache:
      period: 0
  servlet:
    multipart:
      max-file-size: 40MB
      max-request-size: 40MB
#  devtools:
#    restart:
#      poll-interval: 2s
#      quite-period: 1s
#      additional-paths: classpath:/templates/

server:
  tomcat:
    accesslog:
      enabled: true
